# Generated by Django 5.1.2 on 2024-10-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('identificador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ruta_directorio', models.CharField(max_length=500)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_inicio_programado', models.TimeField()),
                ('hr_termino_programado', models.TimeField()),
                ('hr_inicio_efectivo', models.TimeField(blank=True, null=True)),
                ('hr_termino_efectivo', models.TimeField(blank=True, null=True)),
                ('duracion_clase', models.DurationField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.tipoclase')),
            ],
        ),
    ]
