# Generated by Django 5.1.2 on 2024-10-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('administrativo', '0001_initial'),
        ('personas', '0001_initial'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.alumno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='diagnostico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programa.diagnostico'),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.alumno'),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura'),
        ),
        migrations.AddField(
            model_name='notasalumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso'),
        ),
        migrations.AddField(
            model_name='progresoalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.alumno'),
        ),
        migrations.AddField(
            model_name='progresoalumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso'),
        ),
        migrations.AddField(
            model_name='sede',
            name='coordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.coordinador'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.sede'),
        ),
    ]
