# Generated by Django 5.1.2 on 2024-10-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.alumno')),
                ('apoderado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.apoderado')),
                ('calificacion_docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.calificaciondocente')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.clase')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.docente')),
                ('motivo_cierre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.motivoclase')),
            ],
        ),
    ]
